version: 2
jobs:
  build_web:
    docker:
      - image: circleci/node:10.16.2
    working_directory: ~/repo/web
    steps:
      - checkout
      - run: 
          name: build web
          command: |
            cd web
            yarn
            yarn test
            cd ..
  build_app:
    docker:
      - image: circleci/python:2.7.16
      - image: circleci/node:10.16.2
    working_directort: ~/repo/app
    steps:
      - checkout
      - run: 
          name: build app
          command: |
          cd app
          yarn install 
          yarn test
          cd ..

  build_contracts:
    docker:
      - image: circleci/node:10.16.2
    working_directort: ~/repo/contracts
    steps:
      - checkout
      - run: 
          name: build contracts
          command: 
            cd contracts
            yarn install
            yarn test
workflows:
  version: 2
  build:
    jobs:
      - build_web
      - build_app
      - build_contracts
